### PR TITLE
Krystelle - error message not serving meals

### LINKED ISSUE #5: BUG: Bad UX on days where UCSB Dining isn't serving meals
If you access the app on a day when the UCSB Dining Commons are closed, you get this "toast spam" from backend errors.

Image

Steps to reproduce:

1. Access link, hard coding a day when a dining commons was closed:  https://dining.dokku-06.cs.ucsb.edu/diningcommons/2025-08-16/carrillo

Expected: A reasonable message informing users that this dining commons is not serving meals on that particular day.

Observed: Toast spam with backend error messages.

# Suggestion

Make backend return a reasonable error code, intercept it, and display a reasonable message for the user.

Note that there is an more sophisticated approach that can *also* be implemented; see issue `FEATURE: Show meals on page where you can select a dining commons.`.   

This issue is for the simplest thing that could possibly work, and may be moot if that other issue is done first.

### PR DESCRIPTION
**Pull request by krystelleb22**
CLOSES #5 

I fixed the UX Bug so that when a UCSB dining common is closed, it instead shows the toast spam message as "[diningCommon] is closed on [date]. Please select another date or dining common." rather than a backend error message. 

Dokku: https://dining-dev-krystelleb22.dokku-08.cs.ucsb.edu/diningcommons/2025-08-16/carrillo

Screenshot 2025-11-19 at 10 56 36 PM

### CODE REVIEW

**Review by varsha-nara — DISMISSED** [review]
Looks good!

File: frontend/src/main/utils/useBackend.jsx [hunk 1]
```diff
@@ -2,29 +2,6 @@ import { useQuery, useMutation, useQueryClient } from "react-query";
 import axios from "axios";
 import { toast } from "react-toastify";
 
-// example
```
Comment (pconrad) [inline frontend/src/main/utils/useBackend.jsx]: Why were these comments removed?  This is not commented out code, but rather it is documentation for this module.  

Can we restore this?
